language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
en:
 - CI=true
 
before_install:
 - npm i -g mirror-config-china --registry=https://registry.npm.taobao.org
 
script:
  yarn build

branches:
  only:
  - gh-pages

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main
